import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/js/auth/login.js',
                'resources/js/auth/register.js',
                'resources/js/auth/otp.js',
                'resources/js/admin/dashboard.js',
                'resources/css/admin.css',
                'resources/css/website.css',
                'resources/js/website/website.js',
                'resources/css/auth/login.css',
                'resources/css/user.css',
                'resources/js/admin/alumni.js',
                'resources/js/admin/alumniadmin.js',
                'resources/js/admin/approvalpengajuandana.js',
                'resources/js/admin/berita.js',
                'resources/js/admin/biodata.js',
                'resources/js/admin/artikel.js',
                'resources/js/admin/pengajuandana.js',
                'resources/js/admin/herosection.js',
                'resources/js/admin/kategorisoal.js',
                'resources/js/admin/kontak.js',
                'resources/js/admin/menu.js',
                'resources/js/admin/mitra.js',
                'resources/js/admin/nilai.js',
                'resources/js/admin/pbsaktif.js',
                'resources/js/admin/pendaftaranpbs.js',
                'resources/js/admin/pengurus.js',
                'resources/js/admin/permission.js',
                'resources/js/admin/pertanyaan.js',
                'resources/js/admin/soal.js',
                'resources/js/admin/pilihan.js',
                'resources/js/admin/opsi.js',
                'resources/js/admin/kategoripotensiakademik.js',
                'resources/js/admin/potensiakademiksoal.js',
                'resources/js/admin/program.js',
                'resources/js/admin/riwayatpengajuandana.js',
                'resources/js/admin/roles.js',
                'resources/js/admin/sejarah.js',
                'resources/js/admin/sensasiclub.js',
                'resources/js/admin/submenu.js',
                'resources/js/admin/tahunakademik.js',
                'resources/js/admin/user.js',
                'resources/js/admin/visimisi.js',
            ],
            refresh: true,
        }),
    ],
    server: {
        host: 'localhost',
        port: 5173,
        watch: {
            usePolling: true,
        },
        hmr: {
            host: 'localhost',
        },
    },
});
